// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: protobuf/greetEveryOnePB/greetEveryOnePB.proto

package greetEveryOnePB

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// greet request
type GreetEveryOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GreetEveryOneRequest) Reset() {
	*x = GreetEveryOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetEveryOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetEveryOneRequest) ProtoMessage() {}

func (x *GreetEveryOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetEveryOneRequest.ProtoReflect.Descriptor instead.
func (*GreetEveryOneRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDescGZIP(), []int{0}
}

func (x *GreetEveryOneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// greet response
type GreetEveryOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *GreetEveryOneResponse) Reset() {
	*x = GreetEveryOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetEveryOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetEveryOneResponse) ProtoMessage() {}

func (x *GreetEveryOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetEveryOneResponse.ProtoReflect.Descriptor instead.
func (*GreetEveryOneResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDescGZIP(), []int{1}
}

func (x *GreetEveryOneResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

var File_protobuf_greetEveryOnePB_greetEveryOnePB_proto protoreflect.FileDescriptor

var file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x50, 0x42, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x50, 0x42, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x50,
	0x42, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x72, 0x65, 0x65, 0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a,
	0x15, 0x47, 0x72, 0x65, 0x65, 0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x32, 0x74, 0x0a, 0x14, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5c, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12, 0x25, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x50, 0x42, 0x2e, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x26, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65,
	0x50, 0x42, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1b,
	0x5a, 0x19, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x50, 0x42, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDescOnce sync.Once
	file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDescData = file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDesc
)

func file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDescGZIP() []byte {
	file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDescOnce.Do(func() {
		file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDescData)
	})
	return file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDescData
}

var file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_goTypes = []interface{}{
	(*GreetEveryOneRequest)(nil),  // 0: greetEveryOnePB.GreetEveryOneRequest
	(*GreetEveryOneResponse)(nil), // 1: greetEveryOnePB.GreetEveryOneResponse
}
var file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_depIdxs = []int32{
	0, // 0: greetEveryOnePB.GreetEveryOneService.Greet:input_type -> greetEveryOnePB.GreetEveryOneRequest
	1, // 1: greetEveryOnePB.GreetEveryOneService.Greet:output_type -> greetEveryOnePB.GreetEveryOneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_init() }
func file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_init() {
	if File_protobuf_greetEveryOnePB_greetEveryOnePB_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetEveryOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetEveryOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_goTypes,
		DependencyIndexes: file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_depIdxs,
		MessageInfos:      file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_msgTypes,
	}.Build()
	File_protobuf_greetEveryOnePB_greetEveryOnePB_proto = out.File
	file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_rawDesc = nil
	file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_goTypes = nil
	file_protobuf_greetEveryOnePB_greetEveryOnePB_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreetEveryOneServiceClient is the client API for GreetEveryOneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetEveryOneServiceClient interface {
	// unary API
	Greet(ctx context.Context, opts ...grpc.CallOption) (GreetEveryOneService_GreetClient, error)
}

type greetEveryOneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetEveryOneServiceClient(cc grpc.ClientConnInterface) GreetEveryOneServiceClient {
	return &greetEveryOneServiceClient{cc}
}

func (c *greetEveryOneServiceClient) Greet(ctx context.Context, opts ...grpc.CallOption) (GreetEveryOneService_GreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetEveryOneService_serviceDesc.Streams[0], "/greetEveryOnePB.GreetEveryOneService/Greet", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetEveryOneServiceGreetClient{stream}
	return x, nil
}

type GreetEveryOneService_GreetClient interface {
	Send(*GreetEveryOneRequest) error
	Recv() (*GreetEveryOneResponse, error)
	grpc.ClientStream
}

type greetEveryOneServiceGreetClient struct {
	grpc.ClientStream
}

func (x *greetEveryOneServiceGreetClient) Send(m *GreetEveryOneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetEveryOneServiceGreetClient) Recv() (*GreetEveryOneResponse, error) {
	m := new(GreetEveryOneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetEveryOneServiceServer is the server API for GreetEveryOneService service.
type GreetEveryOneServiceServer interface {
	// unary API
	Greet(GreetEveryOneService_GreetServer) error
}

// UnimplementedGreetEveryOneServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetEveryOneServiceServer struct {
}

func (*UnimplementedGreetEveryOneServiceServer) Greet(GreetEveryOneService_GreetServer) error {
	return status.Errorf(codes.Unimplemented, "method Greet not implemented")
}

func RegisterGreetEveryOneServiceServer(s *grpc.Server, srv GreetEveryOneServiceServer) {
	s.RegisterService(&_GreetEveryOneService_serviceDesc, srv)
}

func _GreetEveryOneService_Greet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetEveryOneServiceServer).Greet(&greetEveryOneServiceGreetServer{stream})
}

type GreetEveryOneService_GreetServer interface {
	Send(*GreetEveryOneResponse) error
	Recv() (*GreetEveryOneRequest, error)
	grpc.ServerStream
}

type greetEveryOneServiceGreetServer struct {
	grpc.ServerStream
}

func (x *greetEveryOneServiceGreetServer) Send(m *GreetEveryOneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetEveryOneServiceGreetServer) Recv() (*GreetEveryOneRequest, error) {
	m := new(GreetEveryOneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GreetEveryOneService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greetEveryOnePB.GreetEveryOneService",
	HandlerType: (*GreetEveryOneServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Greet",
			Handler:       _GreetEveryOneService_Greet_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/greetEveryOnePB/greetEveryOnePB.proto",
}
